- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: upgrade packages
  become: yes
  apt:
    update_cache: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: Download zsh installer
  get_url: 
    url: https://deb.nodesource.com/setup_13.x 
    dest: /tmp/setup_13.sh
    
- name: Execute the setup_13.sh
  become: true
  become_user: root 
  shell: chmod 777 setup_13.sh & bash setup_13.sh
  args:
    chdir: /tmp/

- name: "upgrade"
  become: true
  command: apt-get install -y nodejs
  args:
    chdir: /root

- name: "install pm2"
  become: true
  command: npm install --global pm2