groups:
- name: Down
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 1m
    labels:
      severity: 'critical'
    annotations:
      title: 'Instance {{$label.instance}} down'
      summary: "Instance  is down"
      description: " of job  has been down for more than 1 minute."