- name: Creates Directory
  become: yes
  file:
    path: ~/backend
    state: directory
    mode: 0777

- name: test
  become: yes
  shell: |
    ls

- name: Copy backend dist files web server
  become: yes
  copy:
    src:  /root/project/artifact.tar.gz
    dest: /home/ubuntu/backend/artifact.tar.gz

- name: Extract backend files
  become: yes
  shell: |
    cd ~/backend
    tar -vxf artifact.tar.gz

- name: "Start app"
  become: true
  shell: |
    sudo pm2 stop default
    pm2 start npm -- start "backend" -- run start
  args:
    chdir: /root/backend
  register: shell_output

- name: PM2 start main
  become: true
  command: pm2 start main.js --update-env
  args:
    chdir: /root/backend/dist    
  register: shell_output